eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/book_service
    username: postgres
    password: bookservice_db_password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9094

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        bookEvents-out-0:
          destination: book-events
          contentType: application/json

        loanCreated-in-0:
          destination: loan-created-topic
          contentType: application/json

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
