eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/book_service
    username: postgres
    password: bookservice_db_password
    driver-class-name: org.postgresql.Driver

  cloud:
    function:
      # Bean isimleri birebir: loanCreated(), loanReturned()
      definition: loanCreated;loanReturned

    stream:
      default-binder: kafka

      kafka:
        binder:
          brokers: localhost:9094

      bindings:
        # LoanCreatedEvent consumer
        loanCreated-in-0:
          destination: loancreated-events
          group: book-service
          content-type: application/json

        # LoanReturnedEvent consumer
        loanReturned-in-0:
          destination: loanreturn-events
          group: book-service
          content-type: application/json

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
