
services:
  membersv_db:
    container_name: membersv_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: member_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: memberservice_db_password
    ports:
      - "5438:5432"
    volumes:
      - memberdb_vol:/var/lib/postgresql/data

  booksv_db:
    container_name: booksv_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: book_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bookservice_db_password
    ports:
      - "5439:5432"
    volumes:
      - bookdb_vol:/var/lib/postgresql/data

  authorsv_db:
    container_name: authorsv_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: author_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: authorservice_db_password
    ports:
      - "5437:5432"
    volumes:
      - authordb_vol:/var/lib/postgresql/data

  publishersv_db:
    container_name: publishersv_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: publisher_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: publisherservice_db_password
    ports:
      - "5436:5432"
    volumes:
      - publisherdb_vol:/var/lib/postgresql/data
 
  staffsv_db:
    container_name: staffsv_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: staff_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: staffservice_db_password
    ports:
      - "5442:5432"
    volumes:
      - staffdb_vol:/var/lib/postgresql/data
      
 loansv_db:
    container_name: loansv_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: loan_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: loanservice_db_password
    ports:
      - "5440:5432"
    volumes:
      - loandb_vol:/var/lib/postgresql/data

volumes:
  memberdb_vol:
  bookdb_vol:
  authordb_vol:
  publisherdb_vol:
  staffdb_vol:
  loandb_vol:
  

  
