
services:
  membersv_db:
    container_name: membersv_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: member_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: memberservice_db_password
    ports:
      - "5438:5432"
    volumes:
      - memberdb_vol:/var/lib/postgresql/data

  authorsv_db:
    container_name: authorsv_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: author_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: authorservice_db_password
    ports:
      - "5439:5432"
    volumes:
      - authordb_vol:/var/lib/postgresql/data

  loansv_db:
    container_name: loansv_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: loan_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: loanservice_db_password
    ports:
      - "5440:5432"
    volumes:
      - loandb_vol:/var/lib/postgresql/data

volumes:
  memberdb_vol:
  authordb_vol:
  loandb_vol:
