eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/member_service
    username: postgres
    password: memberservice_db_password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9094

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        memberEvents-out-0:
          destination: member-events
          contentType: application/json

        fineCreated-in-0:
          destination: member-events
          group: member-service
          contentType: application/json
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
