eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/reservation_service
    username: postgres
    password: reservationservice_db_password
    driver-class-name: org.postgresql.Driver

  cloud:
    function:
      # Bean isimleriyle birebir aynı olmalı
      definition: loanCreatedReservation;loanReturnedReservation

    stream:
      default-binder: kafka

      kafka:
        binder:
          brokers: localhost:9094

      bindings:
        # LoanCreatedEvent consumer (reservation tarafı)
        loanCreatedReservation-in-0:
          destination: loancreated-events
          group: reservation-service
          content-type: application/json

        # LoanReturnedEvent consumer (reservation tarafı)
        loanReturnedReservation-in-0:
          destination: loanreturn-events
          group: reservation-service
          content-type: application/json

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
