spring:
  application:
    name: publisher-service
  datasource:
    url: jdbc:postgresql://localhost:5436/publisher_service
    username: postgres
    password: publisherservice_db_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8086
