spring:
  application:
    name: member-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8787

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
