eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/staff_service
    username: postgres
    password: staffservice_db_password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9094

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        staffEvents-out-0:
          destination: staff-events
          contentType: application/json

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
