management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  kafka:
    bootstrap-servers: localhost:9094

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9094
