eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/fine_service
    username: postgres
    password: fineservice_db_password
    driver-class-name: org.postgresql.Driver

  cloud:
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        fineCreated-out-0:
          destination: member-events
          content-type: application/json

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
