spring:
  application:
    name: reservation-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8787
  cloud:
    stream:
      default-binder: kafka
      bindings:
        loanReturnedConsumer-in-0:
          destination: loan-returned
          group: reservation-service
      kafka:
        binder:
          brokers: kafka:9092
