eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/loan_service
    username: postgres
    password: loanservice_db_password
    driver-class-name: org.postgresql.Driver

  cloud:
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        loanCreated-out-0:
          destination: loan-created-topic
          contentType: application/json
        loanReturned-out-0:
          destination: loan-returned-topic
          contentType: application/json

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
